### ISSUE TITLE
Possible problems with getMinYear (and possibly other parts of database too?)

### ISSUE THREAD

**Issue by LukasBlumer** [LukasBlumer/AvengerMovieDB#13]
As far as I can tell, getMinYear currently includes the -1 from the movies we have that do not have release year information. 

I think these should probably be excluded from getMinYear for the column chart converter (I'm actually not sure whether there is a case at all in which they would have to be included when searching for a minyear - ideas?)

Alternatively I can try to sort them out in the converter but as multiple classes might have an issue with this, it seems to make more sense to fix in the getMinYear method.

**Comment by LukasBlumer** [comment]
I'll try looking into this.

**Comment by pwittw** [comment]
It was an error that occurred when setting minYear while creating the MovieCollection from an arrayList.
Other word for error here is poor planning.
Anyway it's fixed.
