### ISSUE TITLE
Bind Map legend max to country with most movies automatically

### ISSUE THREAD

**Issue by LukasBlumer** [LukasBlumer/AvengerMovieDB#5]
At the moment I've hardcoded it to 35'000 but ideally it should be tied to the country with the max amount of movies automatically.

We'll need a method like getCountryWithMaxMovies() or something like that so that is possible though. Possibly just set that variable after text file import so that it doesn't have to be recalculated every time it is needed as the database only changes on recompile anyway.

**Comment by LukasBlumer** [comment]
Alright, to get this to work properly, because US has 33'000 to the second countrie's 7000 or so, we'll probably have to look into implementing another color point so the difference between the lower amounts is more obvious.

Currently we're hardcoded it to 10000 max and hidden the legend but that doesn't work so well if we assume we might get more data sets with more movies in them. The upper bound needs to scale automatically.

**Comment by pwittw** [comment]
If you don't set any max value at all it will automatically be set to the largest occurring value.
The maxValue method is only needed if you want to set the maxValue to something else.
