### ISSUE TITLE
Failsafe for MovieCollectionCoverter

### ISSUE THREAD

**Issue by LukasBlumer** [LukasBlumer/AvengerMovieDB#7]
We need a failsafe for the converter so that the app as a whole can continue working.

e.g. when the MovieCollection is empty, send an empty dataTable to the map / table / charts (since they are all based on dataTables) so that they are displayed, even though empty. (looks better than error message, should probably log that even though).

Also make sure to differentiate to when the filters set to something that has no results - for example movies made between 2000 and 2001 in a land in which during that timeframe no movies were released.

**Comment by pwittw** [comment]
Does sending a null database need to be differentiated from having no results other than a log message?

Otherwise I've fixed it, Will be integrated in my next push.

**Comment by LukasBlumer** [comment]
I think that should be fine.

Marking as closed.
